
plugins {
    id 'java'
    id 'idea'
    id 'maven-publish'
    id "net.fabricmc.fabric-loom" version "$fabric_loom_version"
}

base {
    archivesName = "${mod_id}"
}

dependencies {

    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    implementation project(":common")
    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:${mixin_extras_version}")))
    implementation "maven.modrinth:konkrete:1.11.1-26.2-fabric"
    implementation "maven.modrinth:modmenu:20.0.0-beta.4"

    implementation "maven.modrinth:AANobbMI:3QgJXuSK" // Sodium
    implementation "maven.modrinth:PtjYWJkn:9M5lqgDj" // Sodium Extra
    implementation "maven.modrinth:Bh37bMuy:6in8I1ms" // Reese's Sodium Options
    implementation "maven.modrinth:gvQqBUqZ:vy3clWg7" // Lithium
    implementation "maven.modrinth:YL57xq9U:3uIIps8q" // Iris
    implementation "maven.modrinth:5ZwdcRci:4r0uMdy5" // ImmediatelyFast
    implementation "maven.modrinth:uXXizFIs:d5ddUdiB" // FerriteCore
    implementation "maven.modrinth:1eAoo2KR:LlSShNCR" // YACL
    implementation "maven.modrinth:G1hIVOrD:R4NA8OoZ" // Resourceful Lib
    implementation "maven.modrinth:9KawNmQc:Cj9TTwYh" // FrozenLib
    implementation "maven.modrinth:1oUDhxuy:QbfNnjo9" // Moog's Structure Lib
    implementation "maven.modrinth:NNAgCjsB:iiF6U3Ne" // Entity Culling
    implementation "maven.modrinth:BVzZfTc1:HLCBKYFD" // Entity Texture Features
    implementation "maven.modrinth:4I1XuqiY:xQeW3qQB" // Entity Model Features
    implementation "maven.modrinth:MPCX6s5C:67xQnLDS" // Not Enough Animations
    implementation "maven.modrinth:zV5r3pPn:rJYtiDew" // 3D Skin Layers
    implementation "maven.modrinth:XaDC71GB:v0V661Hk" // Lithostitched
    implementation "maven.modrinth:8oi3bsk5:SlY1ZV8Z" // Terralith
    implementation "maven.modrinth:hl5OLM95:jDzSPLta" // Geophilic
    implementation "maven.modrinth:lNDRiXkY:dOfY3eZf" // Variants&Ventures
    implementation "maven.modrinth:AtHRJSUW:TVkz6cZh" // Wilder Wild
    implementation "maven.modrinth:V6LLU8Gf:yyyqupBe" // Katters Structures
    implementation "maven.modrinth:rYlnn25U:bSQbtn5T" // AdoraBuild: Structures
    implementation "maven.modrinth:OQAgZMH1:cvepxaBC" // MVS - Moog's Voyager Structures

}

loom {
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet("main", ":common")
        }
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run_client")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run_server")
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    source(project(":common").sourceSets.main.allSource)
}
tasks.withType(Javadoc).configureEach {
    source(project(":common").sourceSets.main.allJava)
}
tasks.withType(Test).configureEach {
    // Allow builds when there are test sources but no matching tests.
    failOnNoDiscoveredTests = false
}
tasks.named("sourcesJar", Jar) {
    from(project(":common").sourceSets.main.allSource)
}

processResources {
    from project(":common").sourceSets.main.resources
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            url "file://" + System.getenv("local_maven")
        }
    }
}
